name: BugPilot â€“ SQL Injection Scan

on:
  workflow_dispatch:

jobs:
  sqli_scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - run: pip install -r requirements.txt

    - name: Run SQLi Scan
      env:
        ENABLED_MODULE: sqli
      run: python3 main.py

    - uses: actions/upload-artifact@v4
      with:
        name: sqli-report
        path: reports/output/*.md
