name: BugPilot â€“ SSRF Scan

on:
  workflow_dispatch:

jobs:
  ssrf_scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - run: pip install -r requirements.txt

    - name: Run SSRF Scan
      env:
        ENABLED_MODULE: ssrf
      run: python3 main.py

    - uses: actions/upload-artifact@v4
      with:
        name: ssrf-report
        path: reports/output/*.md
